### ISSUE TITLE
no install module

### ISSUE THREAD

**Issue by preetamhegde** [ONLYOFFICE/onlyoffice-drupal#16]
Drupal Core 9.4
1. composer require drupal/onlyoffice
Could not find package drupal/onlyoffice.
Did you mean this?
drupal/drupal_onlyoffice (its another old module no for Drupal 9x)

2. composer require "firebase/php-jwt": "^4.0 | ^5.0" (ok)
and manual install files : onlyoffice-drupal-1.0.1.tar.gz
in web-gui include is:
The website encountered an unexpected error. Please try again later.

in logs:
`ParseError: syntax error, unexpected ':', expecting ')' in Composer\Autoload\includeFile() (line 208 of /var/www/html/drupal/modules/onlyoffice-drupal-1.0.1/src/Controller/OnlyofficeEditorController.php)`

**Comment by aleksandrfedorov97** [comment]
https://github.com/ONLYOFFICE/onlyoffice-drupal/commit/8752dd13d9060d1e4160206a8dbece4be4381dde
